# Generated by Django 2.2.2 on 2022-01-13 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('男性', '男性'), ('女性', '女性')], default='男性', verbose_name='性別', max_length=2),
            preserve_default=True,
        ),
    ]
