# Generated by Django 2.2.2 on 2022-01-13 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.IntegerField(choices=[(0, '男性'), (1, '女性')], verbose_name='性別'),
        ),
    ]
