# Generated by Django 2.2.2 on 2022-01-31 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_planning', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='plan_id',
        ),
    ]
